"""empty message

Revision ID: 0ec80657d1d5
Revises: 
Create Date: 2019-01-23 15:22:30.428575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec80657d1d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER_REGISTRATIONS', 'userId',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER_REGISTRATIONS', 'userId',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
