"""empty message

Revision ID: 1f9dfc884296
Revises: 
Create Date: 2019-01-23 16:31:34.361467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9dfc884296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('assignedUser', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('assignmentId', sa.Integer(), nullable=False))
    op.add_column('assignments', sa.Column('assignmentName', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('createdUser', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('roomId', sa.Integer(), nullable=True))
    op.drop_column('assignments', 'roomid')
    op.drop_column('assignments', 'assignmentname')
    op.drop_column('assignments', 'createduser')
    op.drop_column('assignments', 'assigneduser')
    op.add_column('rooms', sa.Column('roomId', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('roomName', sa.String(), nullable=True))
    op.drop_column('rooms', 'roomid')
    op.drop_column('rooms', 'roomname')
    op.add_column('user_registrations', sa.Column('entryId', sa.Integer(), nullable=False))
    op.add_column('user_registrations', sa.Column('roomId', sa.Integer(), nullable=True))
    op.add_column('user_registrations', sa.Column('userId', sa.String(), nullable=True))
    op.drop_column('user_registrations', 'entryid')
    op.drop_column('user_registrations', 'roomid')
    op.drop_column('user_registrations', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('userid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_registrations', sa.Column('roomid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_registrations', sa.Column('entryid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user_registrations', 'userId')
    op.drop_column('user_registrations', 'roomId')
    op.drop_column('user_registrations', 'entryId')
    op.add_column('rooms', sa.Column('roomname', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('roomid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('rooms', 'roomName')
    op.drop_column('rooms', 'roomId')
    op.add_column('assignments', sa.Column('assigneduser', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('createduser', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('assignmentname', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assignments', sa.Column('roomid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assignments', 'roomId')
    op.drop_column('assignments', 'createdUser')
    op.drop_column('assignments', 'assignmentName')
    op.drop_column('assignments', 'assignmentId')
    op.drop_column('assignments', 'assignedUser')
    # ### end Alembic commands ###
